#!/bin/bash
echo  "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address          State       PID/Program name "   
echo "tcp        0      0 0.0.0.0:902             0.0.0.0:*               LISTEN      -                   "
echo "tcp        0      0 0.0.0.0:8999            0.0.0.0:*               LISTEN      -                   "